version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.16.2
    steps:
      - checkout
      - run: make release
      - persist_to_workspace:
          root: ~/project
          paths:
            - bin/
  test:
    docker:
      - image: golang:1.16.2
    steps:
      - checkout
      - run: make test-coverage
  release:
    environment:
      CIRCLE_PROJECT_USERNAME: cloudskiff
      CIRCLE_PROJECT_REPONAME: lambda-env-updater
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n ${CIRCLE_TAG} ${CIRCLE_TAG} ./bin/
workflows:
  push:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
  release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - release:
          context: driftctl
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/