version: 2.1
only_branches: &only_branches
  filters:
    branches:
      ignore:
        - main
orbs:
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: golang:1.16.2
    steps:
      - checkout
      - run: make release
      - persist_to_workspace:
          root: ~/project
          paths:
            - bin/
  test:
    docker:
      - image: golang:1.16.2
    steps:
      - checkout
      - run: make test-coverage
  release:
    environment:
      CIRCLE_PROJECT_USERNAME: cloudskiff
      CIRCLE_PROJECT_REPONAME: lambda-env-updater
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n ${CIRCLE_TAG} ${CIRCLE_TAG} ./bin/
  security-oss:
    docker:
        - image: cimg/go:1.16.2
    steps:
        - checkout
        - snyk/scan:
              severity-threshold: medium
              monitor-on-build: true
              project: ${CIRCLE_PROJECT_REPONAME}
              organization: snyk-iac-group-seceng
  security-code:
    docker:
        - image: cimg/go:1.17.2
    steps:
        - checkout
        - snyk/scan:
              command: code test
              severity-threshold: medium
              monitor-on-build: false
              project: ${CIRCLE_PROJECT_REPONAME}
              organization: snyk-iac-group-seceng
workflows:
  push:
    jobs:
      - test:
        <<: *only_branches
      - security-code:
          filters:
            branches:
              # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
              ignore: /pull\/[0-9]+/
          name: Snyk code
          context:
            - snyk
          <<: *only_branches
      - security-oss:
          filters:
            branches:
              # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
              ignore: /pull\/[0-9]+/
          name: Snyk test
          context:
            - snyk
          <<: *only_branches
  release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - release:
          context: lambda-env-updater
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
